# Site settings
title: Klise # site title
description: >- # site description
  He's writing in Bahasa about web technology and experience as a journal
  for documentation things that he learned, meet him <a href="https://github.com/piharpi" target="_blank" rel="noopener">@github</a>.
lang: en-US # default lang
timezone: Asia/Jakarta # set your timezone
image: assets/img/ogp.png # This image used for Open Graph more info https://ogp.me/
repo: https://github.com/piharpi/jekyll-klise # site repo [optional]
mode: dark # default theme "dark" | "light"

# Profile settings
author:
  name: Username # author name
  bio: >- # tell to the world
    This author biography
  username: username # general username
  github: github_username # github username
  twitter: twitter_username # twitter username
  facebook: facebook_username # facebook username
  email: your-email@email.com # email adress
  avatar: /assets/img/avatar.jpg # change with your own avatar

# URL settings
url: ""
baseurl: ""

google_analytics: # leave it blank if not wish
fb_appid:

# Markdown settings
markdown: kramdown
highlighter: rouge
kramdown:
  syntax_highlighter: rouge

defaults: # https://jekyllrb.com/docs/configuration/front-matter-defaults/
  - scope:
      path: ""
      type: posts
    values:
      layout: post
      comments: false
      toc: true
      permalink: /:title/

# Jekyll Compose default front matter
jekyll_compose:
  post_default_front_matter:
    modified:
    tags: []
    description:
  draft_default_front_matter:
    modified:
    tags: []
    description:

# Homepage limit posts
number_of_posts: 5

# Build settings
theme: klise2

sass:
  style: compressed

include:
  - _redirects
  - .htaccess

exclude:
  - CNAME
  - Gemfile
  - Gemfile.lock
  - LICENSE
  - CHANGELOG.md
  - README.md
  - node_modules
  - CODE_OF_CONDUCT.md
  - CONTRIBUTING.md
  - lighthouse.png
  - klise-*.gem
  - klise.gemspec
